languageCode = "en-us"
title = "Olivier Ligot - Blog"
baseURL = "https://www.oligot.be/"
theme = "terminal"

[params]
  author = "Olivier Ligot"
  show_menu = true
  themeColor = "green"
  [params.logo]
    logoText = "Home"
