languageCode = "en-us"
title = "Olivier Ligot - Blog"
baseurl = "https://www.oligot.be/"
theme = "after-dark"

[params]
  author = "Olivier Ligot"
  show_menu = true

[menu]
  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"
