languageCode = "en-us"
title = "Olivier Ligot - Blog"
baseURL = "https://www.oligot.be/"
theme = "cactus-plus"

[params]
  author = "Olivier Ligot"
  show_menu = true

[menu]
  [[menu.main]]
    name = "Home"
    weight = 0
    identifier = "home"
    url = "/"
