languageCode = "en-us"
title = "Olivier Ligot - Blog"
baseURL = "https://www.oligot.be/"

[module]
  [[module.imports]]
    path = 'github.com/panr/hugo-theme-terminal/v4'

[params]
  author = "Olivier Ligot"
  show_menu = true
  themeColor = "green"
  [params.logo]
    logoText = "Home"
